version: '3.8'

networks:
  laravel:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: "laravel_bridge"
    ipam:
      driver: default
      config:
        - subnet: "172.28.0.0/16"
          gateway: "172.28.0.1"
        - subnet: "fd00:dead:beef::/48"
          gateway: "fd00:dead:beef::1"
    enable_ipv6: true
    internal: false
services:
  app:
    container_name: XMex
    build:
      context: .
      dockerfile: dockerfiles/nginx.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    ports:
      - "8082:80"
    volumes:
      - ./:/var/www/html:delegated
    depends_on:
      - php
      - mysql
      - redis
    networks:
      - laravel
    
   
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_XMex
    ports:
      - "8070:80"
    env_file:
      - ".env"
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_PORT=3306
      - PMA_USER=root
      - PMA_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
    restart: always
    depends_on:
      - mysql
    networks:
      - laravel
      
  mysql:
    image: mariadb:10.6
    container_name: mysql_XMex
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    volumes:
      - ./my.cnf:/etc/mysql/my.cnf  
    env_file:
      - ".env"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_USER: ${MYSQL_ROOT_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - laravel
    
  php:
    container_name: php_XMex
    build:
      context: .
      dockerfile: dockerfiles/php.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    ports:
      - "9000:9000"
    volumes:
      - ./:/var/www/html:delegated
    networks:
      - laravel
    command: >
      sh -c "
      /usr/local/bin/wait-for-it.sh mysql:3306 --timeout=60 -- \
      composer install && \
      php artisan migrate --seed && \
      php artisan db:seed --class=StockSymbolsSeeder && \
      php artisan stocks:fetch && \
      php artisan cache:update
      "

  scheduler:
    build:
      context: .
      dockerfile: dockerfiles/php.root.dockerfile
    container_name: scheduler_XMex
    volumes:
      - .:/var/www/html
    depends_on:
      - app
    entrypoint: ["sh", "-c", "while true; do php artisan schedule:run; sleep 60; done"]
    networks:
      - laravel

  redis:
    container_name: redis_XMex
    image: redis:alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - laravel

  composer:
    container_name: composer_XMex
    build:
      context: .
      dockerfile: dockerfiles/php.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    volumes:
      - ./:/var/www/html
    depends_on:
      - php
    entrypoint: [ 'composer', '--ignore-platform-reqs' ]
    networks:
      - laravel
      
  artisan:
    container_name: artisan_XMex
    build:
      context: .
      dockerfile: dockerfiles/php.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    volumes:
      - ./:/var/www/html:delegated
    depends_on:
      - mysql
    entrypoint: >
      sh -c "
      /usr/local/bin/wait-for-it.sh mysql:3306 -- \
      php /var/www/html/artisan
      "
    networks:
      - laravel